# <center> Numpy Basics </center>

In [3]:
#import numpy module with alias np
import numpy as np


We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [4]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
array=np.array([1,2,3])
print(array)


[1 2 3]


In [5]:
# print output
print (array)


[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [6]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])



Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [7]:
#print dimentions of a,b, c and d

print("a=", a,"|Dimensions","---->", a.ndim)
print("b=", b,"|Dimensions","---->", b.ndim)
print("c=", c,"|Dimensions","---->", c.ndim)
print("d=", d,"|Dimensions","---->", d.ndim)




a= 10 |Dimensions ----> 0
b= [1 2 3] |Dimensions ----> 1
c= [[1 2 3]
 [4 5 6]] |Dimensions ----> 2
d= [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] |Dimensions ----> 3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [8]:
# print shape of each a,b ,c and d
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(3,)
(2, 3)
(2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [9]:
# print data type of c and d

print(c.dtype)
print(d.dtype)



int32
int32


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function 

In [10]:
#print type of a and b variable
print(type(a))
print(type(b))




<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
# Lets check length of array b, using len() function
# len(b)

Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy. 

In [12]:
print(len(b))

3


Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [13]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30]
l2 = [40,50,60]
l3 = np.array(l1)
l4 = np.array(l2)

print(l1,l2,l3,l4)



[10, 20, 30] [40, 50, 60] [10 20 30] [40 50 60]


Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [14]:
#code here as instructed above

%timeit [a*b for a,b in zip(l1,l2)]


363 ns ± 5.78 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [15]:
%timeit [c*d for c,d in zip(l3,l4)]

873 ns ± 14.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [16]:
#Create a numpy array using arange with 1 and 11 as parameter in it

arr= np.arange(1,11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [17]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
arr= np.arange(1,11,2)
print(arr)



[1 3 5 7 9]


In [18]:
# create numpy array using eye function with 3 as passed parameter
arr= np.eye(3)
print(arr)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x= np.arange(1,17)
print(x)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [20]:
# Reshape x with 2 rows and 8 columns
x_reshaped= x.reshape(2,8)
print(x_reshaped)
                      

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [21]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:

x_reshaped= x.reshape(2,4,2)
print(x_reshaped)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [22]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4

y_reshaped= x.reshape(4,-1)
print(y_reshaped)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [23]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y= x_reshaped.shape[2]

x_reshaped=x.reshape(2,4,-1)


print(y)



2


In [24]:
# Flattening y


y_flat = x.ravel()
print(y)

2


In [25]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,17,2)


print(a)


[ 2  4  6  8 10 12 14 16]


In [26]:
# Get third element in array a
third_element= a[2]
print(third_element)


6


In [27]:
#Print 3rd, 5th, and 7th element in array a
elements=a[[2,5,7]]
print(elements)



[ 6 12 16]


Lets check the same for 2 D array

In [28]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
# print the 3rd element from the 3rd row of a
new_element= a[2,2]
print(new_element)


9


Well done!

Now lets check indexing for 3 D array 

In [30]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b= np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
print(b[0][1][2])



6


In [32]:
# Create 1D array

arr= np.array([1,2,3,4,5])
print(arr)




[1 2 3 4 5]


In [33]:
# Slice elements from 1st to 5th element from the following array:

sliced= arr[0:5]
print(sliced)



[1 2 3 4 5]


Note: The result includes the start index, but excludes the end index.



In [34]:
# Slice elements from index 5 to the end of the array:

a= np.array([10,20,30,40,50,60,70,80,90])
print(a)

sliced= a[5:]
print(sliced)


[10 20 30 40 50 60 70 80 90]
[60 70 80 90]


In [35]:
    # Slice elements from the beginning to index 5 (not included):

sliced = a[:5]
print(sliced)



[10 20 30 40 50]


**STEP**

Use the step value to determine the step of the slicing:

In [64]:
# Print every other element from index 1 to index 7:

c= a[1:8:2]
print(c)


[20 40 60 80]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [65]:
# Return every other element from the entire array arr:

print(a[::2])


[10 30 50 70 90]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [75]:
# Print array a
x = np.array([[10,20,30,40], [40,50,60,70], [70,80,90,100]])

print(x)


[[ 10  20  30  40]
 [ 40  50  60  70]
 [ 70  80  90 100]]


In [77]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'
sliced= x[2,1:5]
print(sliced)



[ 80  90 100]


In [81]:
# In array 'a' print index 2 from all the elements :

print(x[:,2])



[30 60 90]


In [88]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:

print(x[:,1:])


[[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [102]:
x1= np.array([1,2,3,4,5])
print(x1)



[1 2 3 4 5]


In [103]:
# assign x2 = x1
x2=x1
print(x1)


[1 2 3 4 5]


In [104]:
#print x1 and x2

print(x1,x2)


[1 2 3 4 5] [1 2 3 4 5]


Ok now you have seen that both of them are same 

In [105]:
# change 1st element of x2 as 10
x2[0]= 10
print(x2)


[10  2  3  4  5]


In [106]:
#Again print x1 and x2

print(x1,x2)


[10  2  3  4  5] [10  2  3  4  5]


In [107]:
# Check memory share between x1 and x2
print(np.shares_memory(x1,x2))


True


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [108]:
# Create a view of x1 and store it in x3.
x3= x1.view()
print(x1)
print(x3)

[10  2  3  4  5]
[10  2  3  4  5]


In [109]:
# Again check memory share between x1 and x3

print(np.shares_memory(x1,x3))


True


Woh! simple assignment is similar to view. That means 
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [110]:
#Change 1st element of x3=100
x3[0]= 100
print(x3)


[100   2   3   4   5]


In [111]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)


[100   2   3   4   5]
[100   2   3   4   5]


Now its proved.

Lets see how **Copy()** function works

In [112]:
# Now create an array x4 which is copy of x1

x4= x1.copy()
print(x4)


[100   2   3   4   5]


In [114]:
# Change the last element of x4 as 900

x4[4]= 900
print(x4)



[100   2   3   4 900]


In [115]:
# print both x1 and x4 to check if changes reflected in both

print(x1)
print(x4)


[100   2   3   4   5]
[100   2   3   4 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [116]:
#Check memory share between x1 and x4

print(np.shares_memory(x1,x4))


False


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function: 

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [117]:
# stack x1 and x4 along columns.
result= np.column_stack((x1,x4))
print(result)


[[100 100]
 [  2   2]
 [  3   3]
 [  4   4]
 [  5 900]]


In [118]:
#stack x1 and x4 along rows
result2= np.row_stack((x1,x4))
print(result2)


[[100   2   3   4   5]
 [100   2   3   4 900]]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [120]:
arr1 = np.array([[1,2,3],[4,5,6]])


arr2 = np.array([[10,20,30],[40,50,60]])


##join arr1 and arr2 along rows using concatenate() function
result= np.concatenate((arr1,arr2), axis=0)
print(result)



[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


In [121]:
##join arr1 and arr2 along columns using concatenate() function

result= np.concatenate((arr1,arr2), axis=1)
print(result)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [125]:
# append arr2 to arr1

result= np.append(arr1,arr2)
print(result)

[ 1  2  3  4  5  6 10 20 30 40 50 60]


Lets use insert() function which Inserts values into array before specified index value

In [128]:
# Inserts values into array x1 before index 4 with elements of x4
result= np.insert(x1,4,x4)

print(result)


[100   2   3   4 100   2   3   4 900   5]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [131]:
# delete 2nd element from array x2

result= np.delete(x2,1)
print(result)


[100   3   4   5]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner! 